In [1]:
import tensorflow as tf
from tensorflow.keras import models, layers
import matplotlib.pyplot as plt
from IPython.display import HTML
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [2]:
IMAGE_SIZE = 256
CHANNELS = 3

In [3]:
train_datagen = ImageDataGenerator(
    rescale=1.0/255,
    horizontal_flip=True,
    rotation_range=10
)

train_generator = train_datagen.flow_from_directory(
    'dataset_for_generator/train',
    target_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=32,
    class_mode='sparse',
    # save_to_dir="Augmented_Images"
)


Found 1506 images belonging to 3 classes.


In [4]:
validation_datagen = ImageDataGenerator(
    rescale=1.0/255,
    horizontal_flip=True,
    rotation_range=10
)

validation_generator = validation_datagen.flow_from_directory(
    'dataset_for_generator/val',
    target_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=32,
    class_mode='sparse',
    # save_to_dir="Augmented_Images"
)

Found 215 images belonging to 3 classes.


In [5]:
test_datagen = ImageDataGenerator(
    rescale=1.0/255,
    horizontal_flip=True,
    rotation_range=10
)

test_generator = test_datagen.flow_from_directory(
    'dataset_for_generator/test',
    target_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=32,
    class_mode='sparse',
    # save_to_dir="Augmented_Images"
)

Found 431 images belonging to 3 classes.


In [6]:
for image_batch, label_batch in train_generator:
    print(image_batch[0])
    break

[[[0.64642435 0.61113024 0.6307381 ]
  [0.5966381  0.56134397 0.5809518 ]
  [0.5633675  0.5280734  0.5476812 ]
  ...
  [0.81360745 0.7979212  0.80184275]
  [0.813162   0.79747576 0.8013973 ]
  [0.8127166  0.7970303  0.8009519 ]]

 [[0.64612734 0.6108332  0.63044107]
  [0.5987169  0.5634228  0.58303064]
  [0.5645554  0.5292613  0.54886913]
  ...
  [0.8018512  0.7795559  0.78678197]
  [0.8014058  0.7788135  0.78618807]
  [0.80096036 0.77807105 0.7855941 ]]

 [[0.6458304  0.6105363  0.6301441 ]
  [0.6007957  0.5655016  0.5851094 ]
  [0.5657433  0.5304492  0.55005705]
  ...
  [0.79669833 0.7731689  0.78101206]
  [0.79654986 0.77302045 0.7808636 ]
  [0.7964014  0.772872   0.7807151 ]]

 ...

 [[0.55354017 0.5104029  0.5260892 ]
  [0.55561906 0.5124818  0.5281681 ]
  [0.55769783 0.5145606  0.53024685]
  ...
  [0.7731689  0.7496395  0.7496395 ]
  [0.7770877  0.7535583  0.7535583 ]
  [0.78100646 0.75747705 0.75747705]]

 [[0.60648227 0.563345   0.5796715 ]
  [0.6076702  0.56453294 0.5811563 ]


In [7]:
#building the model
n_classes=3
model = models.Sequential([
    layers.Input(shape=(IMAGE_SIZE, IMAGE_SIZE, CHANNELS)),  # Specify the input shape here
    layers.Conv2D(32, kernel_size=(3,3), activation='relu'), #  performs feature extraction on the image data
    layers.MaxPooling2D((2,2)), # performs a downsampling operation on the feature maps produced by the convolutional layer.(Reduces computational cost, Prevents overfitting)
    layers.Conv2D(64, kernel_size=(3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64, kernel_size=(3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64, kernel_size=(3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64, kernel_size=(3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64, kernel_size=(3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Flatten(), # takes the multi-dimensional output from the last convolutional or pooling layer and "flattens" it into a single, long 1D vector
    layers.Dense(64, activation='relu'), # Dense layers can only process 1D vectors, not multi-dimensional feature maps
    layers.Dense(n_classes, activation='softmax')
])
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 254, 254, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 127, 127, 32)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 125, 125, 64)   │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 62, 62, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 60, 60, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 30, 30, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 28, 28, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 14, 14, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_4 (Conv2D)               │ (None, 12, 12, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_4 (MaxPooling2D)  │ (None, 6, 6, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_5 (Conv2D)               │ (None, 4, 4, 64)       │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_5 (MaxPooling2D)  │ (None, 2, 2, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 64)             │        16,448 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 3)              │           195 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 183,747 (717.76 KB)

 Trainable params: 183,747 (717.76 KB)

 Non-trainable params: 0 (0.00 B)

In [8]:
model.compile(
    optimizer='adam',
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    metrics=['accuracy']
)

In [12]:
model.fit(
    train_generator,
    steps_per_epoch=47, # total_image / batchsize
    batch_size = 32,
    validation_data=validation_generator,
    validation_steps=6,
    verbose=1,
    epochs=20
)

Epoch 1/20
47/47 ━━━━━━━━━━━━━━━━━━━━ 33s 704ms/step - accuracy: 0.8725 - loss: 0.3025 - val_accuracy: 0.8698 - val_loss: 0.2994
Epoch 2/20
47/47 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - accuracy: 0.9375 - loss: 0.2197 - val_accuracy: 0.8698 - val_loss: 0.3290
Epoch 3/20
47/47 ━━━━━━━━━━━━━━━━━━━━ 29s 614ms/step - accuracy: 0.8786 - loss: 0.3051 - val_accuracy: 0.8594 - val_loss: 0.3157
Epoch 4/20
47/47 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - accuracy: 0.9688 - loss: 0.0906 - val_accuracy: 0.8490 - val_loss: 0.3502
Epoch 5/20
47/47 ━━━━━━━━━━━━━━━━━━━━ 29s 604ms/step - accuracy: 0.9132 - loss: 0.2263 - val_accuracy: 0.8802 - val_loss: 0.2625
Epoch 6/20
47/47 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - accuracy: 0.9062 - loss: 0.2242 - val_accuracy: 0.8906 - val_loss: 0.3010
Epoch 7/20
47/47 ━━━━━━━━━━━━━━━━━━━━ 29s 613ms/step - accuracy: 0.9213 - loss: 0.1864 - val_accuracy: 0.9219 - val_loss: 0.1874
Epoch 8/20
47/47 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - accuracy: 0.9375 - loss: 0.0830 - val_accuracy: 0.

In [13]:
scores = model.evaluate(test_generator)
scores

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/keras/src/trainers/data_adapters/py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


14/14 ━━━━━━━━━━━━━━━━━━━━ 3s 200ms/step - accuracy: 0.9466 - loss: 0.1302


[0.13016720116138458, 0.9466357231140137]

In [14]:
model_version=2
model.save(f"{model_version}.keras")